sp:
  sambamba/markdup:
    contents: "finding positions of the duplicate reads in the file"
    num_lines: 8
show_analysis_paths: False
sample_names_replace_regex: True
sample_names_replace:
  "(\\w+)_(markdup)": "\\1"
